"""
Test script for Travel Planner API with Session History Support
Run this after starting the API server
"""

import json
from pprint import pprint

import requests


def test_health_check():
    """Test health check endpoint"""
    print("\n" + "=" * 80)
    print("Testing Health Check Endpoint")
    print("=" * 80)

    response = requests.get("http://localhost:8000/v1/health")
    print(f"Status Code: {response.status_code}")
    print("Response:")
    pprint(response.json())


def test_plan_trip(user_id: str = None):
    """
    Test plan trip endpoint with user tracking
    Session ID will be auto-generated internally by the API

    Args:
        user_id: Optional user ID. If not provided, generates a test user ID
    """
    print("\n" + "=" * 80)
    print("Testing Plan Trip Endpoint (With User Tracking)")
    print("=" * 80)

    # Generate user_id if not provided
    if not user_id:
        # Use your actual user_id here
        user_id = "6986c9c3-947d-4978-88c2-0a2797fdc86c"

    print(f"\n📋 User Information:")
    print(f"   User ID: {user_id}")
    print(f"   → Session ID will be auto-generated by API")
    print(f"   → Chat history between agents will be saved automatically")

    # Sample request with only user_id (session_id is auto-generated internally)
    request_data = {
        "departure_point": "Hanoi",
        "destination": "Seoul, South Korea",
        "departure_date": "2026-02-14",
        "budget": 30000000,
        "num_travelers": 2,
        "trip_duration": 4,
        "travel_style": "self_guided",
        "customer_notes": "Thích ẩm thực Hàn Quốc, Kpop và mua sắm",
        "user_id": user_id,  # Only user_id needed
    }

    print("\nRequest Data:")
    pprint(request_data)

    print("\nSending request (this may take 2-5 minutes)...")
    print("Weather Agent will search for seasonal events and weather forecast...")
    print("Please wait...")

    try:
        response = requests.post(
            "http://localhost:8000/v1/plan_trip",
            json=request_data,
            timeout=900,  # 15 minutes timeout (increased from 10)
        )

        print(f"\nStatus Code: {response.status_code}")

        if response.status_code == 200:
            print("\n✓ Travel plan generated successfully!")
            travel_plan = response.json()

            # Print summary
            print("\n" + "-" * 80)
            print("TRAVEL PLAN SUMMARY")
            print("-" * 80)

            print(f"\nVersion: {travel_plan['version']}")
            print(f"Generated at: {travel_plan['generated_at']}")

            # Itinerary summary
            if travel_plan.get("itinerary"):
                itinerary = travel_plan["itinerary"]
                print(f"\n✓ Itinerary: {len(itinerary['daily_schedules'])} days planned")
                print(f"  Main locations: {', '.join(itinerary['location_list'][:5])}")
                if itinerary.get("selected_flight"):
                    print(f"  Selected Flight: {itinerary['selected_flight']['airline']}")
                if itinerary.get("selected_accommodation"):
                    print(f"  Selected Hotel: {itinerary['selected_accommodation']['name']}")

            # Budget summary
            if travel_plan.get("budget"):
                budget = travel_plan["budget"]
                print(f"\n✓ Budget:")
                print(f"  Total Estimated Cost: {budget['total_estimated_cost']:,.0f} VND")
                print(f"  Budget Status: {budget['budget_status']}")
                print(f"  Categories: {len(budget['categories'])} items")

            # Advisory summary
            if travel_plan.get("advisory"):
                advisory = travel_plan["advisory"]
                print(f"\n✓ Advisory:")
                print(f"  Tips & Warnings: {len(advisory['warnings_and_tips'])} items")
                print(
                    f"  Location Descriptions: {len(advisory['location_descriptions'])} locations"
                )

            # Souvenirs
            if travel_plan.get("souvenirs"):
                print(f"\n✓ Souvenirs: {len(travel_plan['souvenirs'])} suggestions")

            # Logistics
            if travel_plan.get("logistics"):
                logistics = travel_plan["logistics"]
                print(f"\n✓ Logistics:")
                print(f"  Flight Options: {len(logistics['flight_options'])} available")
                print(f"  Average Price: {logistics['average_price']:,.0f} VND/person")

            # Accommodation
            if travel_plan.get("accommodation"):
                accommodation = travel_plan["accommodation"]
                print(f"\n✓ Accommodation:")
                print(f"  Recommendations: {len(accommodation['recommendations'])} options")
                print(f"  Total Estimated: {accommodation['total_estimated_cost']:,.0f} VND")

            # Save to file
            output_file = "travel_plan_output.json"
            with open(output_file, "w", encoding="utf-8") as f:
                json.dump(travel_plan, f, indent=2, ensure_ascii=False)

            print(f"\n✓ Full travel plan saved to: {output_file}")
            print(f"✓ Structured JSON with all fields populated!")

            print(f"\n💡 Session Info:")
            print(f"   User ID: {user_id}")
            print(f"   → Session ID was auto-generated internally")
            print(f"   → Chat history between agents saved to database")
            print(f"   → Check Supabase to see agent conversations")

        else:
            print("\n✗ Error generating travel plan")
            print("Response:")
            pprint(response.json())

    except requests.exceptions.Timeout:
        print("\n✗ Request timeout (>15 minutes)")
        print("The server might still be processing. Check server logs.")
    except requests.exceptions.ConnectionError:
        print("\n✗ Connection error")
        print("Make sure the API server is running at http://localhost:8000")
    except Exception as e:
        print(f"\n✗ Error: {str(e)}")


def test_multi_turn_conversation():
    """
    Test that each API call gets its own session for agent chat history
    Each request is independent - session_id is auto-generated per request
    """
    print("\n" + "=" * 80)
    print("Testing Agent Session History (Auto-Generated Sessions)")
    print("=" * 80)

    # Use your actual user_id
    user_id = "6986c9c3-947d-4978-88c2-0a2797fdc86c"
    destination = "Tokyo, Japan"

    print(f"\n📋 Test Setup:")
    print(f"   User ID: {user_id}")
    print(f"   → Each request will auto-generate its own session_id")
    print(f"   → Session IDs are used internally for agent chat history")

    # =========================================================================
    # TURN 1: Initial 5-day plan
    # =========================================================================
    print(f"\n{'=' * 80}")
    print("🔄 TURN 1: Initial Planning Request (5 days, 30M budget)")
    print("=" * 80)

    request_1 = {
        "departure_point": "Hanoi",
        "destination": destination,
        "departure_date": "2025-12-15",
        "budget": 30000000,
        "num_travelers": 2,
        "trip_duration": 5,
        "travel_style": "self_guided",
        "customer_notes": "We love ramen and want to visit temples",
        "user_id": user_id,
    }

    print("\n📤 Sending Turn 1 request...")
    print(f"   Duration: {request_1['trip_duration']} days")
    print(f"   Budget: {request_1['budget']:,} VND")
    print(f"   This will take 2-5 minutes...")

    try:
        response_1 = requests.post(
            "http://localhost:8000/v1/plan_trip", json=request_1, timeout=900
        )

        if response_1.status_code == 200:
            plan_1 = response_1.json()
            print(f"\n✅ Turn 1 Complete!")
            if plan_1.get("budget"):
                print(f"   Total Cost: {plan_1['budget']['total_estimated_cost']:,.0f} VND")
            print(f"   Session saved to database")

            # Save Turn 1 output
            with open("travel_plan_turn1.json", "w", encoding="utf-8") as f:
                json.dump(plan_1, f, indent=2, ensure_ascii=False)
            print(f"   Saved to: travel_plan_turn1.json")

        else:
            print(f"\n❌ Turn 1 Failed (Status: {response_1.status_code})")
            pprint(response_1.json())
            return

    except Exception as e:
        print(f"\n❌ Turn 1 Error: {str(e)}")
        return

    # =========================================================================
    # TURN 2: Follow-up - Extend to 7 days with higher budget
    # =========================================================================
    print(f"\n{'=' * 80}")
    print("🔄 TURN 2: Second Request (Different plan - 7 days, 40M budget)")
    print("=" * 80)
    print("\n💡 This is a new independent request")
    print("   → Will get its own auto-generated session_id")
    print("   → Agent chat history for this request saved separately")

    request_2 = {
        "departure_point": "Hanoi",
        "destination": destination,
        "departure_date": "2025-12-15",
        "budget": 40000000,  # Increased budget
        "num_travelers": 2,
        "trip_duration": 7,  # Extended duration
        "travel_style": "self_guided",
        "customer_notes": "Plan a 7-day trip with cultural activities focus",
        "user_id": user_id,
    }

    print("\n📤 Sending Turn 2 request...")
    print(f"   Duration: {request_2['trip_duration']} days (extended from 5)")
    print(f"   Budget: {request_2['budget']:,} VND (increased from 30M)")
    print(f"   Notes: '{request_2['customer_notes']}'")
    print(f"   This will take 2-5 minutes...")

    try:
        response_2 = requests.post(
            "http://localhost:8000/v1/plan_trip", json=request_2, timeout=900
        )

        if response_2.status_code == 200:
            plan_2 = response_2.json()
            print(f"\n✅ Turn 2 Complete!")
            if plan_2.get("budget"):
                print(f"   Total Cost: {plan_2['budget']['total_estimated_cost']:,.0f} VND")
            print(f"   Session updated in database")

            # Save Turn 2 output
            with open("travel_plan_turn2.json", "w", encoding="utf-8") as f:
                json.dump(plan_2, f, indent=2, ensure_ascii=False)
            print(f"   Saved to: travel_plan_turn2.json")

            # Compare results
            print(f"\n📊 Comparison:")
            print(f"   Turn 1 → Turn 2")
            if plan_1.get("budget") and plan_2.get("budget"):
                cost_1 = plan_1["budget"]["total_estimated_cost"]
                cost_2 = plan_2["budget"]["total_estimated_cost"]
                print(f"   Cost: {cost_1:,.0f} VND → {cost_2:,.0f} VND")
            print(f"   Duration: 5 days → 7 days")
            print(f"   Budget: 30M VND → 40M VND")

            print(f"\n✅ Two Independent Requests Complete!")
            print(f"   → Each request got its own session_id (auto-generated)")
            print(f"   → Agent chat history saved separately for each request")
            print(f"   → Check Supabase to see 2 different sessions")

        else:
            print(f"\n❌ Turn 2 Failed (Status: {response_2.status_code})")
            pprint(response_2.json())

    except Exception as e:
        print(f"\n❌ Turn 2 Error: {str(e)}")


def test_config():
    """Test config endpoint"""
    print("\n" + "=" * 80)
    print("Testing Config Endpoint")
    print("=" * 80)

    response = requests.get("http://localhost:8000/v1/config")
    print(f"Status Code: {response.status_code}")
    print("Response:")
    pprint(response.json())


if __name__ == "__main__":
    print("\n" + "=" * 80)
    print("TRAVEL PLANNER API - TEST SCRIPT (With Session History)")
    print("=" * 80)
    print("\nMake sure the API server is running:")
    print("  cd src/travel_planner")
    print("  uv run python main.py")
    print("\nThen run this script:")
    print("  uv run python tests/test_api.py")
    print("\n📋 Available Tests:")
    print("  1. Basic tests (health, config)")
    print("  2. Single plan trip (with user_id + session_id)")
    print("  3. Multi-turn conversation (demonstrates session history)")
    print("=" * 80)

    # Ask user which test to run
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "--multi-turn":
        run_multi_turn = True
    else:
        print("\n❓ Which test would you like to run?")
        print("   [1] Quick test - Single plan trip")
        print("   [2] Full test - Multi-turn conversation (takes longer)")
        print("   [Enter] Quick test (default)")

        choice = input("\nYour choice: ").strip()
        run_multi_turn = choice == "2"

    # Run tests
    try:
        test_health_check()
        test_config()

        if run_multi_turn:
            print("\n" + "=" * 80)
            print("Running Full Test - Multi-Turn Conversation")
            print("This will take 5-10 minutes...")
            print("=" * 80)
            test_multi_turn_conversation()
        else:
            print("\n" + "=" * 80)
            print("Running Quick Test - Single Plan Trip")
            print("This will take 2-5 minutes...")
            print("=" * 80)
            test_plan_trip()

    except KeyboardInterrupt:
        print("\n\nTest interrupted by user")
    except Exception as e:
        print(f"\n\nTest failed: {str(e)}")
        import traceback

        traceback.print_exc()

    print("\n" + "=" * 80)
    print("Tests completed")
    print("=" * 80)
    print("\n💡 Session Management:")
    print("   • Users only provide user_id (optional)")
    print("   • API auto-generates session_id for each request")
    print("   • Session stores chat history between agents internally")
    print("   • Each plan request = 1 session with all agent conversations")
    print("   • Check Supabase agent_sessions table to see saved chats")
    print("=" * 80 + "\n")
